### ISSUE TITLE
`unknown option --tapes` on v1.2.17

### ISSUE THREAD

**Issue by cooperka** [airtasker/proxay#151]
On OSX, proxay@1.2.17:

```console
proxay --mode record --host https://example.com --tapes tapes/
error: unknown option `--tapes'
```

Workaround: Downgrade via `yarn global add proxay@1.2.15`

```console
proxay --mode record --host https://example.com --tapes tapes/
Loaded tape: default
Proxying in record mode on port 3000.
```

Thanks for the great work on this! Looking forward to playing around with this more.

**Comment by fwouts** [comment]
Sorry for the delay due to holidays @cooperka. I believe the fix is to use `--tapes-dir` instead. Sorry that we forgot to update the readme!

**Comment by cooperka** [comment]
Thanks for the fix @fwouts! Cheers 🍻
